# Generated by Django 5.2.8 on 2025-11-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Python_Jun',
            fields=[
                ('Name', models.TextField(max_length=100)),
                ('Address', models.TextField(max_length=200)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Marks', models.IntegerField(max_length=3)),
                ('Subject', models.TextField(max_length=100)),
                ('Role_Number', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
