# Generated by Django 5.2.8 on 2025-11-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUDApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='python_jun',
            name='Marks',
            field=models.IntegerField(max_length=100),
        ),
    ]
