# Generated by Django 5.2.8 on 2025-11-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUDApp', '0002_alter_python_jun_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='python_jun',
            name='Marks',
            field=models.IntegerField(),
        ),
    ]
