# Generated by Django 5.2.8 on 2025-11-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUDApp', '0003_alter_python_jun_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='python_jun',
            name='Fees',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='python_jun',
            name='Address',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='python_jun',
            name='Name',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='python_jun',
            name='Subject',
            field=models.TextField(max_length=50),
        ),
    ]
